#!/usr/bin/env python3
"""CPU-only visualization for the software-only stack target demo.

Loads the four robot-frame transforms generated by stack_target_demo.py and
renders:
  - stack_target_3d.png
  - stack_target_side.png
  - stack_target_top.png

No FoundationPose inference, Isaac Sim, or robot commands are used.
"""

import argparse
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_RESULT = ROOT / "g1/results/stack_target_demo"
DEFAULT_BOX_SIZE = np.array([0.40, 0.30, 0.30], dtype=float)

EDGES = [
    (0, 1), (1, 2), (2, 3), (3, 0),
    (4, 5), (5, 6), (6, 7), (7, 4),
    (0, 4), (1, 5), (2, 6), (3, 7),
]


def load_T(path):
    T = np.loadtxt(path).reshape(4, 4)
    if not np.isfinite(T).all():
        raise ValueError(f"Non-finite transform: {path}")
    return T


def box_corners(T, size):
    hx, hy, hz = size / 2.0
    local = np.array([
        [-hx, -hy, -hz], [ hx, -hy, -hz], [ hx,  hy, -hz], [-hx,  hy, -hz],
        [-hx, -hy,  hz], [ hx, -hy,  hz], [ hx,  hy,  hz], [-hx,  hy,  hz],
    ], dtype=float)
    return (T[:3, :3] @ local.T).T + T[:3, 3]


def draw_box_3d(ax, T, size, label):
    c = box_corners(T, size)
    for a, b in EDGES:
        ax.plot([c[a, 0], c[b, 0]], [c[a, 1], c[b, 1]], [c[a, 2], c[b, 2]], linewidth=1.5)
    p = T[:3, 3]
    ax.scatter([p[0]], [p[1]], [p[2]], s=35)
    ax.text(p[0], p[1], p[2], "  " + label, fontsize=9)


def draw_box_2d(ax, T, size, axes, label):
    c = box_corners(T, size)
    if axes == (0, 1):
        idx = [0, 1, 2, 3, 0]
    else:
        # Use a side rectangle that spans the box in x/z.
        idx = [0, 1, 5, 4, 0]
    poly = c[idx][:, list(axes)]
    ax.plot(poly[:, 0], poly[:, 1], linewidth=1.7)
    p = T[:3, 3]
    ax.scatter([p[axes[0]]], [p[axes[1]]], s=35)
    ax.text(p[axes[0]], p[axes[1]], "  " + label, fontsize=9)


def set_equal_3d(ax, points):
    mins = points.min(axis=0)
    maxs = points.max(axis=0)
    center = 0.5 * (mins + maxs)
    radius = max(float(np.max(maxs - mins)) * 0.60, 0.35)
    ax.set_xlim(center[0] - radius, center[0] + radius)
    ax.set_ylim(center[1] - radius, center[1] + radius)
    ax.set_zlim(max(0.0, center[2] - radius), center[2] + radius)


def main():
    ap = argparse.ArgumentParser(description="Visualize carried box A, stack support, target B, and pre-place pose.")
    ap.add_argument("--result-dir", type=Path, default=DEFAULT_RESULT)
    ap.add_argument("--box-size", type=float, nargs=3, default=DEFAULT_BOX_SIZE.tolist(), metavar=("X", "Y", "Z"))
    args = ap.parse_args()

    d = args.result_dir
    size = np.asarray(args.box_size, dtype=float)

    paths = {
        "A carried": d / "T_robot_carried_box.txt",
        "top support": d / "T_robot_top_box.txt",
        "B target": d / "T_robot_place.txt",
        "pre-place": d / "T_robot_preplace.txt",
    }
    missing = [str(p) for p in paths.values() if not p.exists()]
    if missing:
        raise FileNotFoundError("Missing stack-target outputs:\n" + "\n".join(missing))

    T = {name: load_T(path) for name, path in paths.items()}
    centers = np.stack([v[:3, 3] for v in T.values()], axis=0)

    # 3D view.
    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection="3d")
    for name, pose in T.items():
        draw_box_3d(ax, pose, size, name)

    A = T["A carried"][:3, 3]
    B = T["B target"][:3, 3]
    P = T["pre-place"][:3, 3]
    ax.plot([A[0], B[0]], [A[1], B[1]], [A[2], B[2]], linestyle="--", linewidth=1.4, label="A -> B")
    ax.plot([B[0], P[0]], [B[1], P[1]], [B[2], P[2]], linestyle=":", linewidth=1.4, label="placement clearance")
    ax.set_xlabel("robot x [m]")
    ax.set_ylabel("robot y [m]")
    ax.set_zlabel("robot z [m]")
    ax.set_title("Stack target geometry: carried A -> target B")
    set_equal_3d(ax, centers)
    ax.legend()
    fig.tight_layout()
    out3 = d / "stack_target_3d.png"
    fig.savefig(out3, dpi=200)
    plt.close(fig)

    # Side x-z view: best view for checking vertical stacking distance.
    fig, ax = plt.subplots(figsize=(10, 7))
    for name, pose in T.items():
        draw_box_2d(ax, pose, size, (0, 2), name)
    ax.plot([A[0], B[0]], [A[2], B[2]], linestyle="--", linewidth=1.4)
    ax.plot([B[0], P[0]], [B[2], P[2]], linestyle=":", linewidth=1.4)
    ax.set_xlabel("robot x [m]")
    ax.set_ylabel("robot z [m]")
    ax.set_title("Stack target side view (x-z)")
    ax.axis("equal")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    out_side = d / "stack_target_side.png"
    fig.savefig(out_side, dpi=200)
    plt.close(fig)

    # Top x-y view: best view for checking planar alignment/yaw.
    fig, ax = plt.subplots(figsize=(9, 8))
    for name, pose in T.items():
        draw_box_2d(ax, pose, size, (0, 1), name)
    ax.plot([A[0], B[0]], [A[1], B[1]], linestyle="--", linewidth=1.4)
    ax.set_xlabel("robot x [m]")
    ax.set_ylabel("robot y [m]")
    ax.set_title("Stack target top view (x-y)")
    ax.axis("equal")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    out_top = d / "stack_target_top.png"
    fig.savefig(out_top, dpi=200)
    plt.close(fig)

    print("STACK TARGET VISUALIZATION — CPU only")
    print("saved:", out3)
    print("saved:", out_side)
    print("saved:", out_top)
    print("A center:", np.round(A, 4))
    print("B center:", np.round(B, 4))
    print("pre-place center:", np.round(P, 4))


if __name__ == "__main__":
    main()
